import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";
import {
  Download, CheckCircle2, XCircle, Loader2, Copy, RefreshCw,
  Server, Activity, Users, Clock, Terminal, Info, Package
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

// Build the agent PS1 script. Uses array join to avoid backtick conflicts inside JS template literals.
function buildInstallerScript(agentToken, callbackUrl) {
  // BT = PowerShell line-continuation backtick (cannot appear raw in a JS template literal)
  const BT = String.fromCharCode(96);
  const lines = [
    "#Requires -RunAsAdministrator",
    "#Requires -Modules ActiveDirectory",
    "<#",
    ".SYNOPSIS  AD Migration Agent v1.0.0 - Generated by Azure Multi-Tenant Admin Console",
    ".DESCRIPTION",
    "  Scans raw AD (ObjectGUID, SAM, UPN, SID, groups, OUs) and posts results",
    "  to the Admin Console so the AD Migration Wizard can use them.",
    ".REQUIREMENTS",
    "  - Domain-joined Windows Server 2012 R2+ with RSAT AD module",
    "  - Run as Domain Admin (or delegated Read access)",
    "  - PowerShell 5.1+  |  Outbound HTTPS port 443",
    "#>",
    "",
    "param(",
    `  [string]$AgentToken  = "${agentToken}",`,
    `  [string]$CallbackUrl = "${callbackUrl}",`,
    '  [string]$InstallPath = "C:\\ProgramData\\ITAdmin\\ADMigrationAgent",',
    "  [switch]$RunOnce,",
    "  [switch]$Uninstall",
    ")",
    "",
    '$AgentVersion = "1.0.0"',
    '$TaskName     = "ADMigrationAgent"',
    "$LogPath      = \"$InstallPath\\agent.log\"",
    "$AgentIdFile  = \"$InstallPath\\agent.id\"",
    '$ErrorActionPreference = "Stop"',
    "",
    "function Write-Log {",
    '  param([string]$Msg, [string]$Level = "INFO")',
    '  $ts    = Get-Date -Format "yyyy-MM-dd HH:mm:ss"',
    '  $entry = "[$ts][$Level] $Msg"',
    '  Write-Host $entry -ForegroundColor $(if($Level -eq "ERROR"){"Red"} elseif($Level -eq "WARN"){"Yellow"} elseif($Level -eq "OK"){"Green"} else {"Cyan"})',
    "  if ($LogPath) { Add-Content -Path $LogPath -Value $entry -ErrorAction SilentlyContinue }",
    "}",
    "",
    "function Get-OrCreateAgentId {",
    "  if (Test-Path $AgentIdFile) { return (Get-Content $AgentIdFile -Raw).Trim() }",
    "  $id = [System.Guid]::NewGuid().ToString()",
    "  $id | Set-Content $AgentIdFile",
    "  return $id",
    "}",
    "",
    "if ($Uninstall) {",
    '  Write-Log "Uninstalling AD Migration Agent..."',
    "  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue",
    "  Remove-Item -Path $InstallPath -Recurse -Force -ErrorAction SilentlyContinue",
    '  Write-Log "Agent uninstalled." "OK"',
    "  exit 0",
    "}",
    "",
    'Write-Log "=== AD Migration Agent v$AgentVersion Starting ==="',
    "$null = New-Item -ItemType Directory -Force -Path $InstallPath",
    "$AgentId = Get-OrCreateAgentId",
    'Write-Log "Agent ID: $AgentId"',
    'Write-Log "Hostname: $env:COMPUTERNAME"',
    'Write-Log "Callback: $CallbackUrl"',
    "",
    "try {",
    "  Import-Module ActiveDirectory -ErrorAction Stop",
    '  Write-Log "ActiveDirectory module loaded." "OK"',
    "} catch {",
    '  Write-Log "ActiveDirectory module not found. Install RSAT: Add-WindowsFeature RSAT-AD-PowerShell" "ERROR"',
    "  exit 1",
    "}",
    "",
    "function Invoke-ADScan {",
    '  Write-Log "Starting AD scan..."',
    "  $domain = Get-ADDomain",
    '  Write-Log "Domain: $($domain.DNSRoot) | Forest: $($domain.Forest) | NetBIOS: $($domain.NetBIOSName)"',
    "",
    `  $adUsers = Get-ADUser -Filter * -Properties ${BT}`,
    `    ObjectGUID, SamAccountName, UserPrincipalName, DisplayName, GivenName, Surname, ${BT}`,
    `    EmailAddress, Department, Title, Manager, OfficePhone, MobilePhone, ${BT}`,
    `    Enabled, PasswordNeverExpires, PasswordLastSet, LastLogonDate, ${BT}`,
    `    DistinguishedName, MemberOf, SID, mail, whenCreated, whenChanged, SmartcardLogonRequired`,
    "",
    '  Write-Log "Found $($adUsers.Count) users in AD"',
    "",
    "  $users = $adUsers | ForEach-Object {",
    "    $u = $_",
    "    $immutableId = [System.Convert]::ToBase64String($u.ObjectGUID.ToByteArray())",
    "    $grps = @()",
    "    try { $grps = ($u.MemberOf | Select-Object -First 20 | ForEach-Object { ($_ -split ',')[0] -replace '^CN=','' }) } catch {}",
    "    $mgr = ''",
    "    try { if ($u.Manager) { $mgr = (Get-ADUser $u.Manager -Properties SamAccountName).SamAccountName } } catch {}",
    "    [PSCustomObject]@{",
    "      objectGuid=''+$u.ObjectGUID; immutableId=$immutableId; sid=''+$u.SID.Value",
    "      samAccountName=$u.SamAccountName; upn=$u.UserPrincipalName; mail=$u.EmailAddress",
    "      displayName=$u.DisplayName; givenName=$u.GivenName; surname=$u.Surname",
    "      department=$u.Department; title=$u.Title; mobilePhone=$u.MobilePhone",
    "      enabled=$u.Enabled; passwordNeverExpires=$u.PasswordNeverExpires",
    "      passwordLastSet=(''+$u.PasswordLastSet).Trim(); lastLogon=(''+$u.LastLogonDate).Trim()",
    "      distinguishedName=$u.DistinguishedName; ou=($u.DistinguishedName -replace '^CN=[^,]+,','')",
    "      groups=($grps -join '|'); managerSam=$mgr",
    "      whenCreated=(''+$u.whenCreated).Trim(); whenChanged=(''+$u.whenChanged).Trim()",
    "    }",
    "  }",
    "",
    "  $ous = Get-ADOrganizationalUnit -Filter * | Select-Object -First 100 |",
    "    ForEach-Object { @{ name=$_.Name; dn=$_.DistinguishedName } }",
    "  $groups = Get-ADGroup -Filter * | Select-Object -First 200 |",
    "    ForEach-Object { @{ name=$_.Name; category=$_.GroupCategory.ToString(); scope=$_.GroupScope.ToString() } }",
    "  $stats = @{",
    "    totalUsers=$users.Count; enabledUsers=($users|Where-Object{$_.enabled}).Count",
    "    disabledUsers=($users|Where-Object{-not $_.enabled}).Count",
    "    totalGroups=$groups.Count; totalOUs=$ous.Count",
    '    scanTime=(Get-Date -Format "o"); domainFunctionalLevel=$domain.DomainMode.ToString()',
    "  }",
    "  return @{ users=$users; groups=$groups; ous=$ous; stats=$stats",
    "    domain=@{ dns=$domain.DNSRoot; netbios=$domain.NetBIOSName; forest=$domain.Forest } }",
    "}",
    "",
    "function Send-ScanResults { param($SD)",
    '  Write-Log "Sending scan results..."',
    '  $osInfo = "$([System.Environment]::OSVersion.VersionString) | PS $($PSVersionTable.PSVersion)"',
    "  $payload = @{ action='upload_scan'; agent_id=$AgentId; hostname=$env:COMPUTERNAME",
    "    domain=$SD.domain.dns; domain_netbios=$SD.domain.netbios; forest=$SD.domain.forest",
    "    agent_version=$AgentVersion; users=$SD.users; groups=$SD.groups; ous=$SD.ous",
    "    stats=$SD.stats; os_info=$osInfo } | ConvertTo-Json -Depth 6 -Compress",
    '  $headers = @{ "Authorization"="Bearer $AgentToken"; "Content-Type"="application/json" }',
    "  $resp = Invoke-RestMethod -Uri $CallbackUrl -Method POST -Body $payload -Headers $headers -TimeoutSec 120",
    '  if ($resp.success) { Write-Log "Upload OK. ScanId=$($resp.scanId) Users=$($resp.usersReceived)" "OK" }',
    '  else { throw "Upload failed: $($resp.error)" }',
    "}",
    "",
    "try {",
    "  $sd = Invoke-ADScan",
    "  Send-ScanResults -SD $sd",
    "  if (-not $RunOnce) {",
    '    Write-Log "Installing scheduled task (every 4h)..."',
    '    $psPath = $MyInvocation.MyCommand.Path',
    '    $arg = "-ExecutionPolicy Bypass -NonInteractive -File ""$psPath"" -RunOnce"',
    "    $act = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument $arg",
    "    $trg = New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Hours 4) -Once -At (Get-Date)",
    "    $set = New-ScheduledTaskSettingsSet -RunOnlyIfNetworkAvailable -StartWhenAvailable",
    "    $pri = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest",
    "    Register-ScheduledTask -TaskName $TaskName -Action $act -Trigger $trg -Settings $set -Principal $pri -Force | Out-Null",
    '    Write-Log "Scheduled task installed. Re-scans every 4 hours." "OK"',
    "  }",
    '  Write-Log "=== Agent setup complete ===" "OK"',
    "} catch {",
    '  Write-Log "FATAL: $_" "ERROR"',
    "  exit 1",
    "}",
  ];
  return lines.join("\n");
}

function timeAgo(dt) {
  if (!dt) return "Never";
  const diff = Date.now() - new Date(dt).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 2) return "Just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}

export default function AgentDownloadPanel({ onScanLoaded }) {
  const [agentToken, setAgentToken] = useState(null);
  const [copied, setCopied] = useState(false);
  const [selectedScanId, setSelectedScanId] = useState(null);
  const [loadingUsers, setLoadingUsers] = useState(false);

  // Get agent token on mount
  useEffect(() => {
    base44.functions.invoke("adAgentReceiver", { action: "get_agent_token" })
      .then(r => { if (r.data?.agentToken) setAgentToken(r.data.agentToken); })
      .catch(() => {});
  }, []);

  // Build callback URL (the adAgentReceiver function endpoint)
  const callbackUrl = `${window.location.origin.replace(/:\d+$/, "")}/api/functions/adAgentReceiver`;

  const { data: scansData, isLoading: loadingScans, refetch } = useQuery({
    queryKey: ["ad-agent-scans"],
    queryFn: () => base44.functions.invoke("adAgentReceiver", { action: "list_scans" }).then(r => r.data),
    refetchInterval: 15000, // poll every 15s for new scans
  });

  const scans = scansData?.scans || [];

  const handleDownload = () => {
    if (!agentToken) return;
    const script = buildMsiScript(agentToken, callbackUrl);
    const blob = new Blob([script], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "ADMigrationAgent_Setup.ps1";
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyScript = () => {
    if (!agentToken) return;
    const script = buildMsiScript(agentToken, callbackUrl);
    navigator.clipboard.writeText(script);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleLoadScan = async (scanId) => {
    setSelectedScanId(scanId);
    setLoadingUsers(true);
    try {
      const res = await base44.functions.invoke("adAgentReceiver", {
        action: "get_scan_users",
        scan_id: scanId,
      });
      if (res.data?.success && onScanLoaded) {
        onScanLoaded(res.data.users, res.data.scan);
      }
    } catch (e) {
      console.error(e);
    }
    setLoadingUsers(false);
  };

  return (
    <div className="space-y-5">
      {/* Info banner */}
      <div className="bg-violet-50 border border-violet-200 rounded-xl p-4 flex gap-3">
        <Info className="h-5 w-5 text-violet-600 shrink-0 mt-0.5" />
        <div>
          <p className="text-sm font-semibold text-violet-800 mb-1">On-Premises AD Agent</p>
          <p className="text-xs text-violet-700">
            Download and run the PowerShell agent on any <strong>domain-joined Windows Server</strong> with the
            ActiveDirectory module installed. It scans raw AD (ObjectGUID, SAM, UPN, SID, groups, OUs, password policies)
            and securely posts the results back here — no Entra Connect required.
            The agent installs a scheduled task and re-scans every 4 hours.
          </p>
        </div>
      </div>

      {/* Download card */}
      <div className="bg-white border border-slate-200 rounded-xl p-5 space-y-4">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-xl bg-slate-900 flex items-center justify-center">
            <Package className="h-5 w-5 text-emerald-400" />
          </div>
          <div>
            <p className="font-semibold text-slate-800">ADMigrationAgent_Setup.ps1</p>
            <p className="text-xs text-slate-400">PowerShell installer · Runs as SYSTEM · Installs scheduled task</p>
          </div>
        </div>

        <div className="bg-slate-950 rounded-lg p-3 text-xs font-mono">
          <p className="text-slate-500 mb-1"># Deploy on domain controller (run as Administrator):</p>
          <p className="text-emerald-400">powershell.exe -ExecutionPolicy Bypass -File .\ADMigrationAgent_Setup.ps1</p>
          <p className="text-slate-500 mt-2"># Or run once without installing scheduled task:</p>
          <p className="text-emerald-400">powershell.exe -ExecutionPolicy Bypass -File .\ADMigrationAgent_Setup.ps1 -RunOnce</p>
          <p className="text-slate-500 mt-2"># Uninstall:</p>
          <p className="text-amber-400">powershell.exe -ExecutionPolicy Bypass -File .\ADMigrationAgent_Setup.ps1 -Uninstall</p>
        </div>

        <div className="grid grid-cols-3 gap-2 text-xs">
          {[
            { label: "Auth Method", value: "Bearer Token" },
            { label: "Scan Interval", value: "Every 4 hours" },
            { label: "Data Transport", value: "HTTPS POST" },
          ].map(s => (
            <div key={s.label} className="bg-slate-50 rounded-lg p-2.5 text-center">
              <p className="font-semibold text-slate-800">{s.value}</p>
              <p className="text-slate-400 mt-0.5">{s.label}</p>
            </div>
          ))}
        </div>

        <div className="flex gap-2">
          <Button onClick={handleDownload} disabled={!agentToken} className="bg-slate-900 hover:bg-slate-800 text-white gap-2 flex-1">
            <Download className="h-4 w-4" /> Download Agent (.ps1)
          </Button>
          <Button variant="outline" onClick={handleCopyScript} disabled={!agentToken} className="gap-1.5">
            <Copy className="h-4 w-4" /> {copied ? "Copied!" : "Copy Script"}
          </Button>
        </div>

        {!agentToken && (
          <p className="text-xs text-amber-600 flex items-center gap-1">
            <Loader2 className="h-3 w-3 animate-spin" /> Loading agent credentials…
          </p>
        )}
      </div>

      {/* Active Agents / Scan Results */}
      <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
        <div className="flex items-center justify-between px-4 py-3 border-b border-slate-100 bg-slate-50">
          <div className="flex items-center gap-2">
            <Activity className="h-4 w-4 text-slate-500" />
            <p className="text-sm font-semibold text-slate-700">Agent Scan Results</p>
            {scans.length > 0 && <Badge className="bg-emerald-100 text-emerald-700 border-0">{scans.length} agent{scans.length > 1 ? "s" : ""}</Badge>}
          </div>
          <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => refetch()}>
            <RefreshCw className="h-3.5 w-3.5 text-slate-400" />
          </Button>
        </div>

        {loadingScans && (
          <div className="flex justify-center py-8"><Loader2 className="h-5 w-5 animate-spin text-slate-400" /></div>
        )}

        {!loadingScans && scans.length === 0 && (
          <div className="text-center py-10 text-slate-400">
            <Server className="h-8 w-8 mx-auto mb-2 text-slate-200" />
            <p className="text-sm">No agent scans received yet</p>
            <p className="text-xs mt-1">Download and run the agent on your domain controller</p>
          </div>
        )}

        {scans.map(scan => {
          const isSelected = selectedScanId === scan.id;
          const isRecent = scan.scan_time && (Date.now() - new Date(scan.scan_time).getTime()) < 5 * 60 * 60 * 1000;
          return (
            <div key={scan.id} className={`px-4 py-4 border-b border-slate-50 last:border-0 ${isSelected ? "bg-blue-50" : "hover:bg-slate-50"}`}>
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-start gap-3">
                  <div className={`h-2.5 w-2.5 rounded-full mt-1.5 shrink-0 ${isRecent ? "bg-emerald-500 animate-pulse" : "bg-slate-300"}`} />
                  <div>
                    <p className="text-sm font-semibold text-slate-800">{scan.hostname}</p>
                    <p className="text-xs text-slate-500">{scan.domain} · {scan.forest}</p>
                    <div className="flex items-center gap-3 mt-1.5 text-[10px] text-slate-400">
                      <span className="flex items-center gap-1"><Users className="h-2.5 w-2.5" /> {scan.user_count} users</span>
                      <span className="flex items-center gap-1"><Terminal className="h-2.5 w-2.5" /> {scan.group_count} groups</span>
                      <span className="flex items-center gap-1"><Clock className="h-2.5 w-2.5" /> {timeAgo(scan.scan_time)}</span>
                      <span>v{scan.agent_version}</span>
                    </div>
                  </div>
                </div>
                <Button
                  size="sm"
                  onClick={() => handleLoadScan(scan.id)}
                  disabled={loadingUsers && isSelected}
                  className={`text-xs h-8 shrink-0 ${isSelected ? "bg-blue-600 text-white hover:bg-blue-700" : ""}`}
                  variant={isSelected ? "default" : "outline"}
                >
                  {loadingUsers && isSelected
                    ? <Loader2 className="h-3 w-3 animate-spin" />
                    : isSelected ? <CheckCircle2 className="h-3 w-3 mr-1" /> : null
                  }
                  {isSelected ? "Loaded into Wizard" : "Use in Wizard"}
                </Button>
              </div>
            </div>
          );
        })}
      </div>

      {/* Requirements */}
      <div className="bg-slate-50 border border-slate-200 rounded-xl p-4">
        <p className="text-xs font-semibold text-slate-600 uppercase tracking-wide mb-2">Agent Requirements</p>
        <div className="grid grid-cols-2 gap-1.5 text-xs text-slate-600">
          {[
            "Windows Server 2012 R2+",
            "PowerShell 5.1 or later",
            "RSAT: ActiveDirectory module",
            "Domain Admin or delegated Read",
            "Outbound HTTPS (port 443)",
            "Runs as SYSTEM account",
          ].map(r => (
            <div key={r} className="flex items-center gap-1.5">
              <CheckCircle2 className="h-3 w-3 text-emerald-500 shrink-0" />
              {r}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}